#pragma once

ConstantBuffer<GpuDDGIConstants> ddgi : register(b55, space1);

// Debug options /////////////////////////////////////////////////////////
bool show_border_vs_inside() {
    return (ddgi.debug_options & 1) == 1;
}

bool show_border_type() {
    return (ddgi.debug_options & 2) == 2;
}

bool show_border_source_coordinates() {
    return (ddgi.debug_options & 4) == 4;
}

bool use_visibility() {
    return (ddgi.debug_options & 8) == 8;
}

bool use_smooth_backface() {
    return (ddgi.debug_options & 16) == 16;
}

bool use_perceptual_encoding() {
    return (ddgi.debug_options & 32) == 32;
}

bool use_backfacing_blending() {
    return (ddgi.debug_options & 64) == 64;
}

bool use_probe_offsetting() {
    return (ddgi.debug_options & 128) == 128;
}

bool use_probe_status() {
    return (ddgi.debug_options & 256) == 256;
}

bool use_infinite_bounces() {
    return (ddgi.debug_options & 512) == 512;
}

// Probe status //////////////////////////////////////////////////////////
#define PROBE_STATUS_OFF 0
#define PROBE_STATUS_SLEEP 1
#define PROBE_STATUS_ACTIVE 4
#define PROBE_STATUS_UNINITIALIZED 6

// Utility methods ///////////////////////////////////////////////////////
float3 spherical_fibonacci(float i, float n) {
    const float PHI = sqrt(5.0f) * 0.5 + 0.5;
#define madfrac(A, B) ((A) * (B)-floor((A) * (B)))
    float phi       = 2.0 * PI * madfrac(i, PHI - 1);
    float cos_theta = 1.0 - (2.0 * i + 1.0) * (1.0 / n);
    float sin_theta = sqrt(clamp(1.0 - cos_theta * cos_theta, 0.0f, 1.0f));

    return float3(cos(phi) * sin_theta, sin(phi) * sin_theta, cos_theta);

#undef madfrac
}


float sign_not_zero(in float k) {
    return (k >= 0.0) ? 1.0 : -1.0;
}

float2 sign_not_zero2(in float2 v) {
    return float2(sign_not_zero(v.x), sign_not_zero(v.y));
}

// Assumes that v is a unit vector. The result is an octahedral vector on the [-1, +1] square.
float2 oct_encode(in float3 v) {
    float l1norm = abs(v.x) + abs(v.y) + abs(v.z);
    float2 result = v.xy * (1.0 / l1norm);
    if (v.z < 0.0) {
        result = (1.0 - abs(result.yx)) * sign_not_zero(result.xy);
    }
    return result;
}


// Returns a unit vector. Argument o is an octahedral vector packed via oct_encode,
// on the [-1, +1] square
float3 oct_decode(float2 o) {
    float3 v = float3(o.x, o.y, 1.0 - abs(o.x) - abs(o.y));
    if (v.z < 0.0) {
        v.xy = (1.0 - abs(v.yx)) * sign_not_zero2(v.xy);
    }
    return normalize(v);
}

// Compute normalized oct coord, mapping top left of top left pixel to (-1,-1) and bottom right to (1,1)
float2 normalized_oct_coord(int2 fragCoord, int probe_side_length) {

    int probe_with_border_side = probe_side_length + 2;
    float2 octahedral_texel_coordinates = int2((fragCoord.x - 1) % probe_with_border_side, (fragCoord.y - 1) % probe_with_border_side);

    octahedral_texel_coordinates += float2(0.5f);
    octahedral_texel_coordinates *= (2.0f / float(probe_side_length));
    octahedral_texel_coordinates -= float2(1.0f);

    return octahedral_texel_coordinates;
}

float2 get_probe_uv(float3 direction, int probe_index, int full_texture_width, int full_texture_height, int probe_side_length) {

    // Get octahedral coordinates (-1,1)
    const float2 octahedral_coordinates = oct_encode(normalize(direction));
    // TODO: use probe index for this.
    const float probe_with_border_side = float(probe_side_length) + 2.0f;
    const int probes_per_row = (full_texture_width) / int(probe_with_border_side);
    // Get probe indices in the atlas
    int2 probe_indices = int2((probe_index % probes_per_row), 
                               (probe_index / probes_per_row));
    
    // Get top left atlas texels
    float2 atlas_texels = float2( probe_indices.x * probe_with_border_side, probe_indices.y * probe_with_border_side );
    // Account for 1 pixel border
    atlas_texels += float2(1.0f);
    // Move to center of the probe area
    atlas_texels += float2(probe_side_length * 0.5f);
    // Use octahedral coordinates (-1,1) to move between internal pixels, no border
    atlas_texels += octahedral_coordinates * (probe_side_length * 0.5f);
    // Calculate final uvs
    const float2 uv = atlas_texels / float2(float(full_texture_width), float(full_texture_height));
    return uv;
}

float2 texture_coord_from_direction(float3 dir, int probe_index, int full_texture_width, int full_texture_height, int probe_side_length) {
    // Get encoded [-1,1] octahedral coordinate
    float2 normalized_oct_coord = oct_encode(normalize(dir));
    // Map it to [0,1]
    float2 normalized_oct_coord_zero_one = (normalized_oct_coord * 0.5) + 0.5f;

    // Length of a probe side, plus one pixel on each edge for the border
    float probe_with_border_side = float(probe_side_length) + 2.0f;

    float2 oct_coord_normalized_to_texture_dimensions = (normalized_oct_coord_zero_one * float(probe_side_length)) 
                                                    / float2(float(full_texture_width), float(full_texture_height));

    int probes_per_row = (full_texture_width) / int(probe_with_border_side);

    // Add (1,1) back to texCoord within larger texture. Compensates for 1 pix border around top left probe.
    float2 probe_top_left_position = float2((probe_index % probes_per_row) * probe_with_border_side,
        (probe_index / probes_per_row) * probe_with_border_side) + float2(1.0f, 1.0f);

    float2 normalized_probe_top_left_position = float2(probe_top_left_position) / float2(float(full_texture_width), float(full_texture_height));

    return float2(normalized_probe_top_left_position + oct_coord_normalized_to_texture_dimensions);
}

// Probe coordinate system ///////////////////////////////////////////////
int3 probe_index_to_grid_indices( int probe_index ) {
    const int probe_x = probe_index % ddgi.probe_counts.x;
    const int probe_counts_xy = ddgi.probe_counts.x * ddgi.probe_counts.y;

    const int probe_y = (probe_index % probe_counts_xy) / ddgi.probe_counts.x;
    const int probe_z = probe_index / probe_counts_xy;

    return int3( probe_x, probe_y, probe_z );
}

int probe_indices_to_index(in int3 probe_coords) {
    return int(probe_coords.x + probe_coords.y * ddgi.probe_counts.x + probe_coords.z * ddgi.probe_counts.x * ddgi.probe_counts.y);
}

float3 grid_indices_to_world_no_offsets( int3 grid_indices ) {
    return grid_indices * ddgi.probe_spacing + ddgi.probe_grid_position;
}

float3 grid_indices_to_world( int3 grid_indices, int probe_index ) {
    const int probe_counts_xy = ddgi.probe_counts.x * ddgi.probe_counts.y;
    int2 probe_offset_sampling_coordinates = int2(probe_index % probe_counts_xy, probe_index / probe_counts_xy);
    //float3 probe_offset = use_probe_offsetting() ? texelFetch(global_textures[nonuniformEXT(probe_offset_texture_index)], probe_offset_sampling_coordinates, 0).rgb : float3(0);
    float3 probe_offset = use_probe_offsetting() ? texture_2d(ddgi.probe_offset_texture_index).Load( int3(probe_offset_sampling_coordinates, 0)).rgb : float3(0);

    return grid_indices_to_world_no_offsets( grid_indices );// + probe_offset;
}

int3 world_to_grid_indices( float3 world_position ) {
    return clamp(int3((world_position - ddgi.probe_grid_position) * ddgi.reciprocal_probe_spacing), int3(0), ddgi.probe_counts - int3(1));
}

int get_probe_index_from_pixels(int2 pixels, int probe_with_border_side, int full_texture_width) {
    int probes_per_side = full_texture_width / probe_with_border_side;
    return int(pixels.x / probe_with_border_side) + probes_per_side * int(pixels.y / probe_with_border_side);
}

// Sample Irradiance /////////////////////////////////////////////////////

float3 sample_irradiance( float3 world_position, float3 normal, float3 camera_position ) {

    const float3 Wo = normalize(camera_position.xyz - world_position);
    // Bias vector to offset probe sampling based on normal and view vector.
    const float minimum_distance_between_probes = 1.0f;
    float3 bias_vector = (normal * 0.2f + Wo * 0.8f) * (0.75f * minimum_distance_between_probes) * ddgi.self_shadow_bias;

    float3 biased_world_position = world_position + bias_vector;

    // Sample at world position + probe offset reduces shadow leaking.
    int3 base_grid_indices = world_to_grid_indices(biased_world_position);
    float3 base_probe_world_position = grid_indices_to_world_no_offsets( base_grid_indices );

    // alpha is how far from the floor(currentVertex) position. on [0, 1] for each axis.
    float3 alpha = clamp((biased_world_position - base_probe_world_position) , float3(0.0f), float3(1.0f));

    float3 sum_irradiance = float3(0.0f);
    float sum_weight = 0.0f;

    // Iterate over adjacent probe cage
    for (int i = 0; i < 8; ++i) {
        // Compute the offset grid coord and clamp to the probe grid boundary
        // Offset = 0 or 1 along each axis
        int3 offset = int3(i, i >> 1, i >> 2) & int3(1);
        int3 probe_grid_coord = clamp(base_grid_indices + offset, int3(0), ddgi.probe_counts - int3(1));
        int probe_index = probe_indices_to_index(probe_grid_coord);

        // Make cosine falloff in tangent plane with respect to the angle from the surface to the probe so that we never
        // test a probe that is *behind* the surface.
        // It doesn't have to be cosine, but that is efficient to compute and we must clip to the tangent plane.
        float3 probe_pos = grid_indices_to_world(probe_grid_coord, probe_index);

        // Compute the trilinear weights based on the grid cell vertex to smoothly
        // transition between probes. Avoid ever going entirely to zero because that
        // will cause problems at the border probes. This isn't really a lerp. 
        // We're using 1-a when offset = 0 and a when offset = 1.
        float3 trilinear = lerp(1.0 - alpha, alpha, offset);
        float weight = 1.0;

        if ( use_smooth_backface() ) {
            // Computed without the biasing applied to the "dir" variable. 
            // This test can cause reflection-map looking errors in the image
            // (stuff looks shiny) if the transition is poor.
            float3 direction_to_probe = normalize(probe_pos - world_position);

            // The naive soft backface weight would ignore a probe when
            // it is behind the surface. That's good for walls. But for small details inside of a
            // room, the normals on the details might rule out all of the probes that have mutual
            // visibility to the point. So, we instead use a "wrap shading" test below inspired by
            // NPR work.

            // The small offset at the end reduces the "going to zero" impact
            // where this is really close to exactly opposite
            const float dir_dot_n = (dot(direction_to_probe, normal) + 1.0) * 0.5f;
            weight *= (dir_dot_n * dir_dot_n) + 0.2;
        }

        // Bias the position at which visibility is computed; this avoids performing a shadow 
        // test *at* a surface, which is a dangerous location because that is exactly the line
        // between shadowed and unshadowed. If the normal bias is too small, there will be
        // light and dark leaks. If it is too large, then samples can pass through thin occluders to
        // the other side (this can only happen if there are MULTIPLE occluders near each other, a wall surface
        // won't pass through itself.)
        float3 probe_to_biased_point_direction = biased_world_position - probe_pos;
        float distance_to_biased_point = length(probe_to_biased_point_direction);
        probe_to_biased_point_direction *= 1.0 / distance_to_biased_point;

        // Visibility
        if ( use_visibility() ) {

            float2 uv = get_probe_uv(probe_to_biased_point_direction, probe_index, ddgi.visibility_texture_width, ddgi.visibility_texture_height, ddgi.visibility_side_length );

            //float2 visibility = textureLod(global_textures[nonuniformEXT(ddgi.grid_visibility_texture_index)], uv, 0).rg;
            float2 visibility = texture_2d(ddgi.grid_visibility_texture_index).SampleLevel(g_linear_repeat(), uv, 0).rg;

            float mean_distance_to_occluder = visibility.x;

            float chebyshev_weight = 1.0;
            if (distance_to_biased_point > mean_distance_to_occluder) {
                // In "shadow"
                float variance = abs((visibility.x * visibility.x) - visibility.y);
                // http://www.punkuser.net/vsm/vsm_paper.pdf; equation 5
                // Need the max in the denominator because biasing can cause a negative displacement
                const float distance_diff = distance_to_biased_point - mean_distance_to_occluder;
                chebyshev_weight = variance / (variance + (distance_diff * distance_diff));
                
                // Increase contrast in the weight
                chebyshev_weight = max((chebyshev_weight * chebyshev_weight * chebyshev_weight), 0.0f);
            }

            // Avoid visibility weights ever going all of the way to zero because when *no* probe has
            // visibility we need some fallback value.
            chebyshev_weight = max(0.05f, chebyshev_weight);
            weight *= chebyshev_weight;
        }

        // Avoid zero weight
        weight = max(0.000001, weight);

        // A small amount of light is visible due to logarithmic perception, so
        // crush tiny weights but keep the curve continuous
        const float crushThreshold = 0.2f;
        if (weight < crushThreshold) {
            weight *= (weight * weight) * (1.f / (crushThreshold * crushThreshold));
        }

        float2 uv = get_probe_uv(normal, probe_index, ddgi.irradiance_texture_width, ddgi.irradiance_texture_height, ddgi.irradiance_side_length );

        //float3 probe_irradiance = textureLod(global_textures[nonuniformEXT(grid_irradiance_output_index)], uv, 0).rgb;
        float3 probe_irradiance = texture_2d(ddgi.grid_irradiance_output_index).SampleLevel( g_linear_repeat(), uv, 0 ).rgb;

        if ( use_perceptual_encoding() ) {
            probe_irradiance = pow(probe_irradiance, float3(0.5f * 5.0f));
        }

        // Trilinear weights
        weight *= trilinear.x * trilinear.y * trilinear.z + 0.001f;

        sum_irradiance += weight * probe_irradiance;
        sum_weight += weight;
    }

    float3 net_irradiance = sum_irradiance / sum_weight;

    if ( use_perceptual_encoding() ) {
        net_irradiance = net_irradiance * net_irradiance;
    }

    float3 irradiance = 0.5f * PI * net_irradiance * 0.95f;

    return irradiance;
}