#pragma once


// Material calculations /////////////////////////////////////////////////
float4 compute_diffuse_color(inout float4 base_color, uint albedo_texture, float2 uv) {
    if (albedo_texture != INVALID_TEXTURE_INDEX) {
        //float3 texture_colour = remove_srgb( texture(global_textures[nonuniformEXT(albedo_texture)], uv).rgb );
        float3 texture_colour = remove_srgb(texture_2d(albedo_texture).Sample(g_linear_repeat(), uv).rgb);
        base_color *= float4( texture_colour, 1.0 );
    }

    return base_color;
}

float4 compute_diffuse_color_alpha(inout float4 base_color, uint albedo_texture, float2 uv) {
    if (albedo_texture != INVALID_TEXTURE_INDEX) {
        //float4 texture_color = texture(global_textures[nonuniformEXT(albedo_texture)], uv);
        float4 texture_color = texture_2d(albedo_texture).Sample(g_linear_repeat(), uv);
        base_color *= float4( remove_srgb( texture_color.rgb ), texture_color.a );
    }

    return base_color;
}

float3 apply_pixel_normal( uint normal_texture, float2 uv, float3 normal, float3 tangent, float3 bitangent ) {

    if (normal_texture != INVALID_TEXTURE_INDEX) {
        // NOTE(marco): normal textures are encoded to [0, 1] but need to be mapped to [-1, 1] value
        //const float3 bump_normal = normalize( texture(global_textures[nonuniformEXT(normal_texture)], uv).rgb * 2.0 - 1.0 );
        const float3 bump_normal = normalize( texture_2d(normal_texture).Sample(g_linear_repeat(), uv).rgb * 2.0 - 1.0 );
        const float3x3 TBN = float3x3(
            tangent,
            bitangent,
            normal
        );

        // NOTE(marco): we need to transpose the TBN matrix because hlsl treats the vectors in the constructor as rows,
        // glsl as columns
        normal = normalize(mul(transpose(TBN), normalize(bump_normal)));
    }

    return normal;
}

float3 calculate_pbr_parameters( float metalness, float roughness, uint rm_texture, float occlusion, uint occlusion_texture, float2 uv ) {
    if (rm_texture != INVALID_TEXTURE_INDEX) {
        float4 rm = texture_2d(rm_texture).Sample(g_linear_repeat(), uv);

        // Green channel contains roughness values (read as first element in rm)
        roughness *= rm.g;

        // Blue channel contains metalness (read as second element in rm)
        metalness *= rm.b;
    }

    if (occlusion_texture != INVALID_TEXTURE_INDEX) {
        float4 o = texture_2d(occlusion_texture).Sample(g_linear_repeat(), uv);
        // Red channel for occlusion value
        occlusion *= o.r;
    }

    return float3(occlusion, roughness, metalness);
}

float3 calculate_emissive( float3 emissive_color, uint emissive_texture, float2 uv ) {

    if ( emissive_texture != INVALID_TEXTURE_INDEX ) {
        emissive_color *= remove_srgb( texture_2d(emissive_texture).Sample(g_linear_repeat(), uv).rgb );
    }

    return emissive_color;
}

// Apply both alpha mask and/or dithering based on flags
void apply_alpha_discards( uint flags, float alpha, float alpha_cutoff, float2 uv, uint alpha_texture_index ) {

    bool use_alpha_mask = (flags & DrawFlags_AlphaMask) != 0;
    if (use_alpha_mask && alpha < alpha_cutoff) {
        discard;
    }

    bool use_alpha_dither = (flags & DrawFlags_AlphaDither) != 0;
    if ( use_alpha_dither ) {
        //float dithered_alpha = dither(gl_FragCoord.xy, alpha);
        //if (dithered_alpha < 0.001f) {
            //discard;
        //}
    }

    if ( alpha_texture_index != INVALID_TEXTURE_INDEX ) {
        float alpha = texture_2d( alpha_texture_index ).Sample(g_linear_repeat(), uv).r;

        if ( alpha == 0.0 ) {
            discard;
        }
    }
}

// Calculate geometric normal/tangent/bitangent
void calculate_geometric_TBN( inout float3 vertex_normal, inout float3 vertex_tangent, inout float3 vertex_bitangent,
                              float2 uv, float3 vertex_world_position, uint flags, bool is_front_face ) {

    float3 normal = normalize(vertex_normal);
    if ( (flags & DrawFlags_HasNormals) == 0 ) {
        normal = normalize(cross(ddx(vertex_world_position), ddy(vertex_world_position)));
    }

    float3 tangent = normalize(vertex_tangent);
    float3 bitangent = normalize(vertex_bitangent);
    if ( (flags & DrawFlags_HasTangents) == 0 ) {
        float3 uv_dx = ddx(float3(uv, 0.0));
        float3 uv_dy = ddy(float3(uv, 0.0));

        // NOTE(marco): code taken from https://github.com/KhronosGroup/glTF-Sample-Viewer
        float3 t_ = (uv_dy.y * ddx(vertex_world_position) - uv_dx.y * ddy(vertex_world_position)) /
                  (uv_dx.x * uv_dy.y - uv_dy.x * uv_dx.y);
        tangent = normalize(t_ - normal * dot(normal, t_));

        bitangent = cross( normal, tangent );
    }

    if (is_front_face == false) {
        tangent *= -1.0;
        bitangent *= -1.0;
        normal *= -1.0;
    }

    vertex_normal = normal;
    vertex_tangent = tangent;
    vertex_bitangent = bitangent;
}
